build:
  image: ubuntu:trusty
  commands:
    - echo 'OK'

publish:
  docker:
    registry: registry.40ants.com:5000
    repo: allmychanges.com
    tag:
      - latest
      - 1.7.1
    insecure: true
    when:
      branch: master
