# http://tmuxp.readthedocs.org/en/latest/examples.html

session_name: allmychanges
shell_command_before:
  - '[ -f env/bin/activate ] && source env/bin/activate'
  - reset
windows:
  - window_name: editor
    panes:
      - emacs
  - window_name: shell
    panes:
      -
  - window_name: tests
    panes:
      - tdaemon 'nosetests allmychanges/'
  - window_name: backend
    panes:
      - ./manage.py runserver 0.0.0.0:8000
  - window_name: worker
    panes:
      - ./manage.py rqworker

  - window_name: stylus
    panes:
      - node_modules/.bin/stylus --watch --out allmychanges/static/allmychanges/css allmychanges/static/allmychanges/stylus

  - window_name: rqinfo
    panes:
      - rqinfo

  - window_name: log
    panes:
      - ./tail --cross-finger /var/log/allmychanges/django-art.log
